version: '{build}'
os: Visual Studio 2015
build_script:
  - build.bat
test:
  # assemblies to test - optional
  assemblies:
    - BuildDrop\vs15\Test\SonarLocalAnalyser.Test.dll
    - BuildDrop\vs15\Test\SonarRestService.Test.dll
    - BuildDrop\vs15\Test\VSSonarExtensionUi.Test.dll
after_test:
  - cmd: nuget pack VSSonarExtensionPlugin3Api.nuspec
  - cmd: nuget pack VSSonarExtensionPlugin4Api.nuspec
artifacts:
  - path: 'BuildDrop\vs13\VSSonarExtensionMetroVs2013.vsix'
    name: VSSonarExtensionMetroVs2013
  - path: 'BuildDrop\vs15\VSSonarExtensionMetroVs2015.vsix'
    name: VSSonarExtensionMetroVs2015
  - path: 'BuildDrop\vs15\VSSonarExtensionPlugin3Api.nupkg'
    name: VSSonarExtensionPlugin3Api
  - path: 'BuildDrop\vs15\VSSonarExtensionPlugin4Api.nupkg'
    name: VSSonarExtensionPlugin4Api    