image: Visual Studio 2019
version: '{build}'
build_script:
  - msbuild /t:Restore;Build /p:Configuration=Release
test:
  # assemblies to test - optional
  assemblies:
    - BuildDrop\Test\LocalAnalyserTests\SonarAnalyser.Test.dll
    - BuildDrop\Test\JiraPlugin\JiraPlugin.Test.dll
    - BuildDrop\CxxPlugin.Test\CxxPlugin.Test.dll
    - BuildDrop\VSSonarExtensionUi.Test\VSSonarExtensionUi.Test.dll
artifacts:
  - path: 'BuildDrop\vsix\VSSonarExtensionMetroVs2019.vsix'
    name: VSSonarExtensionMetroVs2019
  - path: '*.nupkg'
    name: nugets
